import streamlit as st
import pandas as pd
import os

st.set_page_config(page_title="HSBC Quantum Fraud Dashboard", layout="wide")

st.title("HSBC Quantum-Enhanced Credit Card Fraud Detection")
st.markdown("""
> **[SYNTHETIC] WARNING:** All data displayed in this dashboard is currently generated by the synthetic smoke-test fixture.
> Do not interpret these metrics as real IEEE-CIS results. Real data is blocked by Kaggle credential availability.
""")

st.header("1. Model Performance (AUPRC)")

try:
    results_df = pd.read_csv("data/results/budget_sweep_results.csv")
    b10_result = results_df[results_df['budget'] == 10.0].iloc[0]
    hybrid_auprc = b10_result['hybrid_auprc']
except Exception as e:
    hybrid_auprc = "N/A"

col1, col2, col3 = st.columns(3)
with col1:
    st.metric(label="Classical Incumbent (LightGBM)", value="[PLANNED]", delta="-")
with col2:
    st.metric(label="Classical RBF Control", value=f"{hybrid_auprc:.4f}" if isinstance(hybrid_auprc, float) else hybrid_auprc, delta="N/A")
with col3:
    st.metric(label="Escalation Budget (B%)", value="10.0%", delta=None)

st.header("2. Escalation Architecture")
st.markdown("""
The router escalates the top $B\%$ most uncertain classical predictions to the Control/Expert models.
Currently implemented using a strict 70/10/20 temporal split to prevent distribution leakage.
""")

# Placeholder for Budget vs AUPRC graph
st.info("[PLANNED] Cost vs Budget curve plotting using Plotly.")
